
package AppPackage;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;

public class AdminGUI extends javax.swing.JFrame {

    EmployeeMgmt EMGMT = new EmployeeMgmt();
    dbConnect dbC = new dbConnect();
    
    int yMouse;
    int xMouse;
    String s;
    

    Connection conn;
    Statement stmt;
    String sql;
    ResultSet rs;
    
    
    public AdminGUI() {
        initComponents();
        setTitle("Admin | CTU Employee Information System");
        searchBar.setVisible(false);
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = dbC.getConnection();
            stmt = conn.createStatement();
            String sql = "SELECT message FROM announcements";
            ResultSet rs = stmt.executeQuery(sql);
        //STEP 5: Extract data from result set
        while(rs.next()){
           //Retrieve by column name
           String msg = rs.getString("message");

           s = msg;
      }
      rs.close();
            
        } catch(HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println("Not Connected");
        }

        MarqueePanel mp = new MarqueePanel(s, 105);
        mp.setBackground(new Color(57,66,100));
        announceBar.setBackground(new Color(57,66,100)); 
        announceBar.add(mp);
        announceBar.setVisible(true);
        mp.start();
        
        setTitle("Admin | CTU Employee Information System");
        setIconImage(new ImageIcon(getClass().getResource("/imgPackage/edtrps32x32.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navAttendance = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        settingsBtn = new javax.swing.JLabel();
        announceBtn = new javax.swing.JLabel();
        msgBtn = new javax.swing.JLabel();
        reportBtn = new javax.swing.JLabel();
        payrollBtn = new javax.swing.JLabel();
        userBtn = new javax.swing.JLabel();
        announceBar = new java.awt.Panel();
        winMin = new javax.swing.JLabel();
        winClose = new javax.swing.JLabel();
        winDrag = new javax.swing.JLabel();
        adminBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAttendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navAttendanceMouseExited(evt);
            }
        });
        getContentPane().add(navAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 48, 125, 25));

        searchBar.setBackground(new java.awt.Color(31, 37, 61));
        searchBar.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        searchBar.setForeground(new java.awt.Color(255, 255, 255));
        searchBar.setToolTipText("");
        searchBar.setBorder(null);
        searchBar.setOpaque(false);
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        getContentPane().add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 98, 250, 28));

        settingsBtn.setToolTipText("Settings");
        settingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
        });
        getContentPane().add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 384, 180, 180));

        announceBtn.setToolTipText("Announcement");
        announceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        announceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                announceBtnMouseClicked(evt);
            }
        });
        getContentPane().add(announceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 384, 180, 180));

        msgBtn.setToolTipText("Messages");
        msgBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(msgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 384, 180, 180));

        reportBtn.setToolTipText("Reports");
        reportBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(reportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 158, 180, 180));

        payrollBtn.setToolTipText("Payroll");
        payrollBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payrollBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payrollBtnMouseClicked(evt);
            }
        });
        getContentPane().add(payrollBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 156, 180, 180));

        userBtn.setToolTipText("User Management");
        userBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBtnMouseClicked(evt);
            }
        });
        getContentPane().add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 158, 180, 180));

        announceBar.setBackground(new java.awt.Color(57, 66, 100));
        getContentPane().add(announceBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 614, 930, 48));

        winMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        winMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winMinMouseClicked(evt);
            }
        });
        getContentPane().add(winMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 10, 22, 20));

        winClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        winClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winCloseMouseClicked(evt);
            }
        });
        getContentPane().add(winClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 10, 22, 20));

        winDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                winDragMouseDragged(evt);
            }
        });
        winDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                winDragMousePressed(evt);
            }
        });
        getContentPane().add(winDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1025, 85));

        adminBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPackage/AdminHome.png"))); // NOI18N
        getContentPane().add(adminBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1026, 682));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void winMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winMinMouseClicked
        this.setExtendedState(AttendanceGUI.ICONIFIED);
    }//GEN-LAST:event_winMinMouseClicked

    private void winCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_winCloseMouseClicked

    private void winDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_winDragMouseDragged

    private void winDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_winDragMousePressed

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void userBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBtnMouseClicked
        // TODO add your handling code here:
        EMGMT.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_userBtnMouseClicked

    private void navAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAttendanceMouseEntered
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("/imgPackage/navAttendanceHover.png"));
        navAttendance.setIcon(img);
        navAttendance.setVisible(true);
    }//GEN-LAST:event_navAttendanceMouseEntered

    private void navAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAttendanceMouseExited
        // TODO add your handling code here:
//        ImageIcon img = new ImageIcon(getClass().getResource("/imgPackage/navAttendanceNormal.png"));
        navAttendance.setIcon(null);
//        navAttendance.setVisible(true);
    }//GEN-LAST:event_navAttendanceMouseExited

    private void navAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAttendanceMouseClicked
        // TODO add your handling code here:
        new AttendanceGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_navAttendanceMouseClicked

    private void announceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_announceBtnMouseClicked
        // TODO add your handling code here:
        new AnnouncementsGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_announceBtnMouseClicked

    private void payrollBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollBtnMouseClicked
        // TODO add your handling code here:
        new Payroll().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_payrollBtnMouseClicked

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        // TODO add your handling code here:
        new SettingsGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_settingsBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminBG;
    private java.awt.Panel announceBar;
    private javax.swing.JLabel announceBtn;
    private javax.swing.JLabel msgBtn;
    private javax.swing.JLabel navAttendance;
    private javax.swing.JLabel payrollBtn;
    private javax.swing.JLabel reportBtn;
    private javax.swing.JTextField searchBar;
    private javax.swing.JLabel settingsBtn;
    private javax.swing.JLabel userBtn;
    private javax.swing.JLabel winClose;
    private javax.swing.JLabel winDrag;
    private javax.swing.JLabel winMin;
    // End of variables declaration//GEN-END:variables
}
