/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;


/**
 *
 * @author acer
 */
public class AnnouncementsGUI extends javax.swing.JFrame {

    /**
     * Creates new form AnnouncementsGUI
     */
    dbConnect dbC = new dbConnect();
    
    int yMouse;
    int xMouse;
    Connection conn = null;
    PreparedStatement stmt = null;
    public AnnouncementsGUI() {
        initComponents();
        setTitle("CTU Employee Information System");
        setIconImage(new ImageIcon(getClass().getResource("/imgPackage/edtrps32x32.png")).getImage());
        ARoot.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winClose = new javax.swing.JLabel();
        winMin = new javax.swing.JLabel();
        navAttendance = new javax.swing.JLabel();
        winDrag = new javax.swing.JLabel();
        backHome = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        ARoot = new javax.swing.JPanel();
        ARecents = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeViewTable = new javax.swing.JTable();
        ARecentsBG = new javax.swing.JLabel();
        ANew = new javax.swing.JPanel();
        publishNow = new javax.swing.JLabel();
        aMsgStatus = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        newAnnouncementBox = new javax.swing.JTextArea();
        ANewBG = new javax.swing.JLabel();
        AHome = new javax.swing.JLabel();
        ARecentsBtn = new javax.swing.JLabel();
        ANewBtn = new javax.swing.JLabel();
        AnnouncementsBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        winClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        winClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winCloseMouseClicked(evt);
            }
        });
        getContentPane().add(winClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 10, 22, 20));

        winMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        winMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winMinMouseClicked(evt);
            }
        });
        getContentPane().add(winMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 10, 22, 20));

        navAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAttendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navAttendanceMouseExited(evt);
            }
        });
        getContentPane().add(navAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 48, 125, 25));

        winDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                winDragMouseDragged(evt);
            }
        });
        winDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                winDragMousePressed(evt);
            }
        });
        getContentPane().add(winDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1025, 85));

        backHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backHomeMouseClicked(evt);
            }
        });
        getContentPane().add(backHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 30));

        searchBar.setEditable(false);
        searchBar.setBackground(new java.awt.Color(31, 37, 61));
        searchBar.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        searchBar.setForeground(new java.awt.Color(255, 255, 255));
        searchBar.setBorder(null);
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        getContentPane().add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 98, 250, 28));

        ARoot.setBackground(new java.awt.Color(31, 37, 61));
        ARoot.setLayout(new java.awt.CardLayout());

        ARecents.setBackground(new java.awt.Color(31, 37, 61));
        ARecents.setMaximumSize(new java.awt.Dimension(45, 24));
        ARecents.setMinimumSize(new java.awt.Dimension(45, 24));
        ARecents.setPreferredSize(new java.awt.Dimension(45, 24));
        ARecents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeViewTable.setBackground(new java.awt.Color(24, 31, 51));
        EmployeeViewTable.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        EmployeeViewTable.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Good Morning :)", "1:11:11"},
                {"2", "Good Noon :)", "2:22:22"},
                {"3", "Good AfterNoon :)", "3:33:33"},
                {"4", "Good Evening :)", "4:44:44"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Message", "Date & Time"
            }
        ));
        EmployeeViewTable.setRowHeight(30);
        EmployeeViewTable.setRowSelectionAllowed(false);
        EmployeeViewTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(EmployeeViewTable);

        ARecents.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 670, 340));

        ARecentsBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPackage/AnnouncementsRecent.png"))); // NOI18N
        ARecents.add(ARecentsBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        ARoot.add(ARecents, "card2");

        ANew.setBackground(new java.awt.Color(31, 37, 61));
        ANew.setMaximumSize(new java.awt.Dimension(45, 24));
        ANew.setMinimumSize(new java.awt.Dimension(45, 24));
        ANew.setPreferredSize(new java.awt.Dimension(45, 24));
        ANew.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        publishNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        publishNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                publishNowMouseClicked(evt);
            }
        });
        ANew.add(publishNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 445, 140, 40));

        aMsgStatus.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        aMsgStatus.setForeground(new java.awt.Color(255, 255, 255));
        aMsgStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ANew.add(aMsgStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 360, 30));

        jScrollPane2.setBackground(new java.awt.Color(230, 231, 232));
        jScrollPane2.setBorder(null);

        newAnnouncementBox.setBackground(new java.awt.Color(230, 231, 232));
        newAnnouncementBox.setColumns(20);
        newAnnouncementBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        newAnnouncementBox.setForeground(new java.awt.Color(51, 51, 51));
        newAnnouncementBox.setRows(5);
        newAnnouncementBox.setBorder(null);
        jScrollPane2.setViewportView(newAnnouncementBox);

        ANew.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 156, 570, 255));

        ANewBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPackage/AnnouncementsNew.png"))); // NOI18N
        ANew.add(ANewBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        ARoot.add(ANew, "card2");

        getContentPane().add(ARoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 828, 530));

        AHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AHomeMouseClicked(evt);
            }
        });
        getContentPane().add(AHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 110));

        ARecentsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ARecentsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ARecentsBtnMouseClicked(evt);
            }
        });
        getContentPane().add(ARecentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 280, 140, 50));

        ANewBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ANewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ANewBtnMouseClicked(evt);
            }
        });
        getContentPane().add(ANewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 347, 138, 50));

        AnnouncementsBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPackage/Announcements.png"))); // NOI18N
        getContentPane().add(AnnouncementsBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1026, 682));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void winCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_winCloseMouseClicked

    private void winMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winMinMouseClicked
        this.setExtendedState(AttendanceGUI.ICONIFIED);
    }//GEN-LAST:event_winMinMouseClicked

    private void winDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_winDragMouseDragged

    private void winDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_winDragMousePressed

    private void backHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backHomeMouseClicked
        // TODO add your handling code here:

        new AdminGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backHomeMouseClicked

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void AHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AHomeMouseClicked
        ARoot.setVisible(false);
        aMsgStatus.setText("");
    }//GEN-LAST:event_AHomeMouseClicked

    private void ARecentsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ARecentsBtnMouseClicked
        // TODO add your handling code here:
        ARoot.setVisible(true);
        ARoot.removeAll();
        ARoot.repaint();
        ARoot.revalidate();
        ARoot.add(ARecents);
        ARoot.repaint();
        ARoot.revalidate();
        aMsgStatus.setText("");

    }//GEN-LAST:event_ARecentsBtnMouseClicked

    private void ANewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ANewBtnMouseClicked
        // TODO add your handling code here:
        ARoot.setVisible(true);
        ARoot.removeAll();
        ARoot.repaint();
        ARoot.revalidate();
        ARoot.add(ANew);
        ARoot.repaint();
        ARoot.revalidate();
        aMsgStatus.setText("");
    }//GEN-LAST:event_ANewBtnMouseClicked

    private void publishNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publishNowMouseClicked
        // TODO add your handling code here:
        String newA = newAnnouncementBox.getText();
        if (newA.length()== 0) {
            aMsgStatus.setText("Field can't be empty!");
        } else {
        newAnnouncementBox.setText("");
        aMsgStatus.setText("New Announcement Posted!");
        try {
//            Class.forName("com.mysql.jdbc.Driver");
            conn = dbC.getConnection();
            stmt = conn.prepareStatement("INSERT INTO announcements(message) VALUES (?)");
            stmt.setString(1,newA); 
            stmt.executeUpdate();
         
        }catch(SQLException se){
      //Handle errors for JDBC
      se.printStackTrace();
   }catch(Exception e){
      //Handle errors for Class.forName
      e.printStackTrace();
   }finally{
      //finally block used to close resources
      try{
         if(stmt!=null)
            conn.close();
      }catch(SQLException se){
      }// do nothing
      try{
         if(conn!=null)
            conn.close();
      }catch(SQLException se){
         se.printStackTrace();
      }//end finally try
   }//end try

//end main
        
        }
    }//GEN-LAST:event_publishNowMouseClicked

    private void navAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAttendanceMouseClicked
        // TODO add your handling code here:
        new AttendanceGUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_navAttendanceMouseClicked

    private void navAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAttendanceMouseEntered
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("/imgPackage/navAttendanceHover.png"));
        navAttendance.setIcon(img);
        navAttendance.setVisible(true);
    }//GEN-LAST:event_navAttendanceMouseEntered

    private void navAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAttendanceMouseExited
        // TODO add your handling code here:
        //        ImageIcon img = new ImageIcon(getClass().getResource("/imgPackage/navAttendanceNormal.png"));
        navAttendance.setIcon(null);
        //        navAttendance.setVisible(true);
    }//GEN-LAST:event_navAttendanceMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnnouncementsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnnouncementsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnnouncementsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnnouncementsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnnouncementsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AHome;
    private javax.swing.JPanel ANew;
    private javax.swing.JLabel ANewBG;
    private javax.swing.JLabel ANewBtn;
    private javax.swing.JPanel ARecents;
    private javax.swing.JLabel ARecentsBG;
    private javax.swing.JLabel ARecentsBtn;
    private javax.swing.JPanel ARoot;
    private javax.swing.JLabel AnnouncementsBG;
    private javax.swing.JTable EmployeeViewTable;
    private javax.swing.JLabel aMsgStatus;
    private javax.swing.JLabel backHome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel navAttendance;
    private javax.swing.JTextArea newAnnouncementBox;
    private javax.swing.JLabel publishNow;
    private javax.swing.JTextField searchBar;
    private javax.swing.JLabel winClose;
    private javax.swing.JLabel winDrag;
    private javax.swing.JLabel winMin;
    // End of variables declaration//GEN-END:variables
}
